apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ai-station
  labels: 
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql 
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: v1 
kind: Service 
metadata:
  name: mysql-client
  namespace: ai-station 
  labels:
    app: mysql 
spec:
  type: ClusterIP 
  selector:
    app: mysql 
  ports:
  - name: mysql 
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql 
  namespace: ai-station 
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: mysql
  replicas: 1  
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql 
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets 
              key: DB_NAME
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: app-secrets 
              key: DB_USER
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: app-secrets 
              key: DB_PASS 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage 
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
          