apiVersion: v1 
kind: Namespace 
metadata:
  name: cloudflared
---
apiVersion: v1 
kind: Secret 
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  creds.json: |
    {
      "AccountTag":"937a19799e936a28b84bfe3c37e8eabf",
      "TunnelSecret":"dwd0Rlb/5WAVi6da8M9mRvFj5399PE493g4bobHUAKA=",
      "TunnelID":"2b40ca2b-5ea7-4eb3-962f-0600e051e55c"
    }
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cloudflared 
  namespace: cloudflared 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared 
        image: cloudflare/cloudflared:latest 
        args: 
        - tunnel
        - --no-autoupdate
        - --credentials-file
        - /etc/cloudflared/creds/creds.json
        - run
        - 2b40ca2b-5ea7-4eb3-962f-0600e051e55c
        volumeMounts:
        - name: creds
          mountPath: /etc/cloudflared/creds 
          readOnly: true 
      volumes:
      - name: creds 
        secret:
          secretName: tunnel-credentials
          