apiVersion: v1 
kind: Namespace 
metadata:
  name: cloudflared
---
apiVersion: v1 
kind: Secret 
metadata:
  name: tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  token: eyJhIjoiOTM3YTE5Nzk5ZTkzNmEyOGI4NGJmZTNjMzdlOGVhYmYiLCJ0IjoiODBiN2Q0ZTctMDdmNy00YmRkLWEwYjQtYTIzMmE5YTRhMTcxIiwicyI6IlltTTVOV00xTVRZdFlXTTBaQzAwWm1WaExXRXpZMk10TW1WaE1UYzJOREppTldSaSJ9
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cloudflared 
  namespace: cloudflared 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared 
        image: cloudflare/cloudflared:latest 
        args: ["tunnel","--no-autoupdate","run","--token","$(TUNNEL_TOKEN)"]
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: tunnel-token 
              key: token
              