apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  creds.json: |
    {
      "AccountTag":"937a19799e936a28b84bfe3c37e8eabf",
      "TunnelSecret":"dwd0Rlb/5WAVi6da8M9mRvFj5399PE493g4bobHUAKA=",
      "TunnelID":"2b40ca2b-5ea7-4eb3-962f-0600e051e55c"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 2b40ca2b-5ea7-4eb3-962f-0600e051e55c
    credentials-file: /etc/cloudflared/creds/creds.json

    ingress:
      - hostname: aistation.io.vn
        service: http://frontend.ai-station.svc.cluster.local:80
      - hostname: app.aistation.io.vn
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: docs.aistation.io.vn
        service: http://frontend.ai-station.svc.cluster.local:80
      - hostname: argocd.aistation.io.vn
        service: http://argocd-server.argocd.svc.cluster.local:80
      - service: http_status:404

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: 
        - tunnel 
        - --config 
        - /etc/cloudflared/config/config.yaml
        - --no-autoupdate
        - run
        volumeMounts:
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
      - name: config
        configMap:
          name: cloudflared-config
